### ISSUE TITLE
02-04 Create milestone structure

### ISSUE THREAD

**Issue by bweston26918** [bweston26918/portfolio#1]
# Create a Milestones structure for the Issues section

Milestones are used to track progress on groups of issues or pull requests in a repository.   
Documentation may be found [here](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones).   

***

**Acceptance criteria:**   

- [ ] Go to [Milestones](https://github.com/bweston26918/bweston26918/milestones) page   
- [ ] Determine milestone structure (Title, Due date (optional), Description)   
- [ ] Document milestone structure (store in Drive perhaps)   

***
